import { ConnectionType, ProviderType } from '../constants';
export declare class NetworkDetails {
    private _chainId;
    private _name;
    private _networkType;
    private _logo;
    private _nodeUrl;
    private _explorerTx;
    private _explorerAdr;
    private _networkId;
    private _dPaths;
    constructor(_chainId: number, _name: string, _networkType?: ConnectionType);
    setNodeUrl(value: string): this;
    getNodeUrl(): string;
    setExplorerTxUrl(value: string): this;
    getExplorerTxUrl(): string;
    setExplorerAdrUrl(value: string): this;
    getExplorerAdrUrl(): string;
    setLogo(value: string): this;
    getLogo(): string;
    setNetworkId(value: number): this;
    getNetworkId(): number;
    getChainId(): number;
    getName(): string;
    getNetworkType(): ConnectionType;
    setDPaths(dPaths: Map<ProviderType, string[]>): this;
    getDPaths(): Map<ProviderType, string[]>;
    setWalletDPaths(wallet: ProviderType, paths: string[]): this;
    getWalletDPaths(wallet: ProviderType): string[] | undefined;
}
